package org.qii.weiciyuan.support.smileypicker;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * User: qii
 * Date: 13-10-25
 */
public class EmojiMap {

    private static EmojiMap instance = new EmojiMap();

    private Map<String, String> emoji = new LinkedHashMap<String, String>();

    private EmojiMap() {

//        emoji.put("\u263A", " ");

        emoji.put("\uD83D\uDE04", " ");
        emoji.put("\uD83D\uDE0A", " ");
        emoji.put("\uD83D\uDE03", " ");
        emoji.put("\uD83D\uDE09", " ");
        emoji.put("\uD83D\uDE0D", " ");
        emoji.put("\uD83D\uDE18", " ");
        emoji.put("\uD83D\uDE1A", " ");
        emoji.put("\uD83D\uDE33", " ");
        emoji.put("\uD83D\uDE0C", " ");
        emoji.put("\uD83D\uDE01", " ");
        emoji.put("\uD83D\uDE1C", " ");
        emoji.put("\uD83D\uDE1D", " ");
        emoji.put("\uD83D\uDE12", " ");
        emoji.put("\uD83D\uDE0F", " ");
        emoji.put("\uD83D\uDE13", " ");
        emoji.put("\uD83D\uDE14", " ");
        emoji.put("\uD83D\uDE1E", " ");
        emoji.put("\uD83D\uDE16", " ");
        emoji.put("\uD83D\uDE25", " ");
        emoji.put("\uD83D\uDE30", " ");
        emoji.put("\uD83D\uDE28", " ");
        emoji.put("\uD83D\uDE23", " ");
        emoji.put("\uD83D\uDE22", " ");
        emoji.put("\uD83D\uDE2D", " ");
        emoji.put("\uD83D\uDE02", " ");
        emoji.put("\uD83D\uDE32", " ");
        emoji.put("\uD83D\uDE31", " ");
        emoji.put("\uD83D\uDE20", " ");
        emoji.put("\uD83D\uDE21", " ");
        emoji.put("\uD83D\uDE2A", " ");
        emoji.put("\uD83D\uDE37", " ");
        emoji.put("\uD83D\uDC7F", " ");
        emoji.put("\uD83D\uDC7D", " ");
//        emoji.put("\uD83D\uDC9B", " ");
//        emoji.put("\uD83D\uDC99", " ");
//        emoji.put("\uD83D\uDC9C", " ");
//        emoji.put("\uD83D\uDC97", " ");
//        emoji.put("\uD83D\uDC9A", " ");

        emoji.put("\uD83D\uDC94", " ");
        emoji.put("\uD83D\uDC93", " ");
//        emoji.put("\uD83D\uDC98", " ");
//        emoji.put("\u2728", " ");
//        emoji.put("\uD83C\uDF1F", " ");
//        emoji.put("\uD83D\uDCA2", " ");
//        emoji.put("\u2755", " ");
//        emoji.put("\u2754", " ");
//        emoji.put("\uD83D\uDCA4", " ");
//        emoji.put("\uD83D\uDCA8", " ");
//        emoji.put("\uD83D\uDCA6", " ");
//        emoji.put("\uD83C\uDFB6", " ");
//        emoji.put("\uD83C\uDFB5", " ");
//        emoji.put("\uD83D\uDD25", " ");
//        emoji.put("\uD83D\uDCA9", " ");
        emoji.put("\uD83D\uDC4D", " ");
        emoji.put("\uD83D\uDC4E", " ");
//        emoji.put("\uD83D\uDC4C", " ");
//        emoji.put("\uD83D\uDC4A", " ");
//        emoji.put("\u270A", " ");
//        emoji.put("\u270C", " ");
//        emoji.put("\uD83D\uDC4B", " ");
//        emoji.put("\u270B", " ");
//        emoji.put("\uD83D\uDC50", " ");
//        emoji.put("\uD83D\uDC46", " ");
//        emoji.put("\uD83D\uDC47", " ");
//        emoji.put("\uD83D\uDC49", " ");
//        emoji.put("\uD83D\uDC48", " ");
//        emoji.put("\uD83D\uDE4C", " ");
//        emoji.put("\uD83D\uDE4F", " ");

//        emoji.put("\uD83D\uDC4F", " ");
//        emoji.put("\uD83D\uDCAA", " ");
//        emoji.put("\uD83D\uDEB6", " ");
//        emoji.put("\uD83C\uDFC3", " ");
//        emoji.put("\uD83D\uDC6B", " ");
//        emoji.put("\uD83D\uDC83", " ");
//        emoji.put("\uD83D\uDC6F", " ");
//        emoji.put("\uD83D\uDE46", " ");
//        emoji.put("\uD83D\uDE45", " ");
//        emoji.put("\uD83D\uDC81", " ");
//        emoji.put("\uD83D\uDE47", " ");
//        emoji.put("\uD83D\uDC8F", " ");
//        emoji.put("\uD83D\uDC91", " ");
//        emoji.put("\uD83D\uDC86", " ");
//        emoji.put("\uD83D\uDC87", " ");
//        emoji.put("\uD83D\uDC85", " ");
//        emoji.put("\uD83D\uDC66", " ");
//        emoji.put("\uD83D\uDC67", " ");
//        emoji.put("\uD83D\uDC69", " ");
//        emoji.put("\uD83D\uDC68", " ");
//        emoji.put("\uD83D\uDC76", " ");
//        emoji.put("\uD83D\uDC75", " ");
//        emoji.put("\uD83D\uDC74", " ");

//        emoji.put("\uD83D\uDC77", " ");
//        emoji.put("\uD83D\uDC6E", " ");
//        emoji.put("\uD83D\uDC7C", " ");
//        emoji.put("\uD83D\uDC78", " ");
//        emoji.put("\uD83D\uDC82", " ");
//        emoji.put("\uD83D\uDC80", " ");
//        emoji.put("\uD83D\uDC63", " ");
//        emoji.put("\uD83D\uDC8B", " ");
//        emoji.put("\uD83D\uDC44", " ");
//        emoji.put("\uD83D\uDC42", " ");
//        emoji.put("\uD83D\uDC40", " ");
//        emoji.put("\uD83D\uDC43", " ");
//        emoji.put("\uD83C\uDF8D", " ");
//        emoji.put("\uD83D\uDC9D", " ");
//        emoji.put("\uD83C\uDF8E", " ");
//        emoji.put("\uD83C\uDF92", " ");
//        emoji.put("\uD83C\uDF93", " ");
//        emoji.put("\uD83C\uDF8F", " ");
//        emoji.put("\uD83C\uDF86", " ");
//        emoji.put("\uD83C\uDF87", " ");
//        emoji.put("\uD83C\uDF90", " ");
//        emoji.put("\uD83C\uDF91", " ");
//        emoji.put("\uD83C\uDF83", " ");
//        emoji.put("\uD83D\uDC7B", " ");
//        emoji.put("\uD83C\uDF85", " ");
//        emoji.put("\uD83C\uDF84", " ");
//        emoji.put("\uD83C\uDF81", " ");
//        emoji.put("\uD83D\uDD14", " ");
//        emoji.put("\uD83C\uDF89", " ");
//        emoji.put("\uD83C\uDF88", " ");
//        emoji.put("\uD83D\uDCBF", " ");
//        emoji.put("\uD83D\uDCC0", " ");
//        emoji.put("\uD83D\uDCF7", " ");
//        emoji.put("\uD83C\uDFA5", " ");
//        emoji.put("\uD83D\uDCBB", " ");
//        emoji.put("\uD83D\uDCFA", " ");
//        emoji.put("\uD83D\uDCF1", " ");
//        emoji.put("\uD83D\uDCE0", " ");
//        emoji.put("\u260E", " ");
//        emoji.put("\uD83D\uDCBD", " ");
//        emoji.put("\uD83D\uDCFC", " ");
//        emoji.put("\uD83D\uDD0A", " ");
//        emoji.put("\uD83D\uDCE2", " ");
//        emoji.put("\uD83D\uDCE3", " ");
//        emoji.put("\uD83D\uDCFB", " ");
//        emoji.put("\uD83D\uDCE1", " ");
//        emoji.put("\u27BF", " ");
//        emoji.put("\uD83D\uDD0D", " ");
//        emoji.put("\uD83D\uDD13", " ");
//        emoji.put("\uD83D\uDD12", " ");
//        emoji.put("\uD83D\uDD11", " ");
//        emoji.put("\u2702", " ");
//        emoji.put("\uD83D\uDD28", " ");
//        emoji.put("\uD83D\uDCA1", " ");
//        emoji.put("\uD83D\uDCF2", " ");
//        emoji.put("\uD83D\uDCE9", " ");
//        emoji.put("\uD83D\uDCEB", " ");
//        emoji.put("\uD83D\uDCEE", " ");
//        emoji.put("\uD83D\uDEC0", " ");
//        emoji.put("\uD83D\uDEBD", " ");
//        emoji.put("\uD83D\uDCBA", " ");
//        emoji.put("\uD83D\uDCB0", " ");
//        emoji.put("\uD83D\uDD31", " ");
//        emoji.put("\uD83D\uDEAC", " ");
//        emoji.put("\uD83D\uDCA3", " ");
//        emoji.put("\uD83D\uDD2B", " ");
//        emoji.put("\uD83D\uDC8A", " ");
//        emoji.put("\uD83D\uDC89", " ");
//        emoji.put("\uD83C\uDFC8", " ");
//        emoji.put("\uD83C\uDFC0", " ");
//        emoji.put("\u26BD", " ");
//        emoji.put("\u26BE", " ");
//        emoji.put("\uD83C\uDFBE", " ");
//        emoji.put("\u26F3", " ");
//        emoji.put("\uD83C\uDFB1", " ");
//        emoji.put("\uD83C\uDFCA", " ");
//        emoji.put("\uD83C\uDFC4", " ");
//        emoji.put("\uD83C\uDFBF", " ");
//        emoji.put("\u2660", " ");
//        emoji.put("\u2665", " ");
//        emoji.put("\u2663", " ");
//        emoji.put("\u2666", " ");
//        emoji.put("\uD83C\uDFC6", " ");
//        emoji.put("\uD83D\uDC7E", " ");
//        emoji.put("\uD83C\uDFAF", " ");
//        emoji.put("\uD83C\uDC04", " ");
//        emoji.put("\uD83C\uDFAC", " ");
//        emoji.put("\uD83D\uDCDD", " ");
//        emoji.put("\uD83D\uDCD6", " ");
//        emoji.put("\uD83C\uDFA8", " ");
//        emoji.put("\uD83C\uDFA4", " ");
//        emoji.put("\uD83C\uDFA7", " ");
//        emoji.put("\uD83C\uDFBA", " ");
//        emoji.put("\uD83C\uDFB7", " ");
//        emoji.put("\uD83C\uDFB8", " ");
//        emoji.put("\u303D", " ");
//        emoji.put("\uD83D\uDC5F", " ");
//        emoji.put("\uD83D\uDC61", " ");
//        emoji.put("\uD83D\uDC60", " ");
//        emoji.put("\uD83D\uDC62", " ");
//        emoji.put("\uD83D\uDC55", " ");
//        emoji.put("\uD83D\uDC54", " ");
//        emoji.put("\uD83D\uDC57", " ");
//        emoji.put("\uD83D\uDC58", " ");
//        emoji.put("\uD83D\uDC59", " ");
//        emoji.put("\uD83C\uDF80", " ");
//        emoji.put("\uD83C\uDFA9", " ");
//        emoji.put("\uD83D\uDC51", " ");
//        emoji.put("\uD83D\uDC52", " ");
//        emoji.put("\uD83C\uDF02", " ");
//        emoji.put("\uD83D\uDCBC", " ");
//        emoji.put("\uD83D\uDC5C", " ");
//        emoji.put("\uD83D\uDC84", " ");
//        emoji.put("\uD83D\uDC8D", " ");
//        emoji.put("\uD83D\uDC8E", " ");

//        emoji.put("\uD83C\uDF75", " ");
//        emoji.put("\uD83C\uDF7A", " ");
//        emoji.put("\uD83C\uDF7B", " ");
//        emoji.put("\uD83C\uDF78", " ");
//        emoji.put("\uD83C\uDF76", " ");
//        emoji.put("\uD83C\uDF74", " ");
//        emoji.put("\uD83C\uDF54", " ");
//        emoji.put("\uD83C\uDF5F", " ");
//        emoji.put("\uD83C\uDF5D", " ");
//        emoji.put("\uD83C\uDF5B", " ");
//        emoji.put("\uD83C\uDF71", " ");
//        emoji.put("\uD83C\uDF63", " ");
//        emoji.put("\uD83C\uDF59", " ");
//        emoji.put("\uD83C\uDF58", " ");
//        emoji.put("\uD83C\uDF5A", " ");
//        emoji.put("\uD83C\uDF5C", " ");
//        emoji.put("\uD83C\uDF72", " ");
//        emoji.put("\uD83C\uDF5E", " ");
//        emoji.put("\uD83C\uDF73", " ");
//
//        emoji.put("\uD83C\uDF62", " ");
//        emoji.put("\uD83C\uDF61", " ");
//        emoji.put("\uD83C\uDF66", " ");
//        emoji.put("\uD83C\uDF67", " ");
//        emoji.put("\uD83C\uDF82", " ");
//        emoji.put("\uD83C\uDF70", " ");
//        emoji.put("\uD83C\uDF4E", " ");
//        emoji.put("\uD83C\uDF4A", " ");
//        emoji.put("\uD83C\uDF49", " ");
//        emoji.put("\uD83C\uDF53", " ");
//        emoji.put("\uD83C\uDF46", " ");
//        emoji.put("\uD83C\uDF45", " ");
//        emoji.put("\u2600", " ");
//        emoji.put("\u2614", " ");
//        emoji.put("\u2601", " ");
//        emoji.put("\u26C4", " ");
//        emoji.put("\uD83C\uDF19", " ");
//        emoji.put("\u26A1", " ");
//        emoji.put("\uD83C\uDF00", " ");
//        emoji.put("\uD83C\uDF0A", " ");
//        emoji.put("\uD83D\uDC31", " ");
//        emoji.put("\uD83D\uDC36", " ");
//        emoji.put("\uD83D\uDC2D", " ");
//        emoji.put("\uD83D\uDC39", " ");
//        emoji.put("\uD83D\uDC30", " ");
//        emoji.put("\uD83D\uDC3A", " ");
//        emoji.put("\uD83D\uDC38", " ");
//        emoji.put("\uD83D\uDC2F", " ");
//        emoji.put("\uD83D\uDC28", " ");
//        emoji.put("\uD83D\uDC3B", " ");
//        emoji.put("\uD83D\uDC37", " ");
//        emoji.put("\uD83D\uDC2E", " ");
//        emoji.put("\uD83D\uDC17", " ");
//        emoji.put("\uD83D\uDC35", " ");
//        emoji.put("\uD83D\uDC12", " ");
//        emoji.put("\uD83D\uDC34", " ");
//        emoji.put("\uD83D\uDC0E", " ");
//        emoji.put("\uD83D\uDC2B", " ");
//        emoji.put("\uD83D\uDC11", " ");
//        emoji.put("\uD83D\uDC18", " ");
//        emoji.put("\uD83D\uDC0D", " ");
//        emoji.put("\uD83D\uDC26", " ");
//        emoji.put("\uD83D\uDC24", " ");
//        emoji.put("\uD83D\uDC14", " ");
//        emoji.put("\uD83D\uDC27", " ");
//        emoji.put("\uD83D\uDC1B", " ");
//        emoji.put("\uD83D\uDC19", " ");
//        emoji.put("\uD83D\uDC20", " ");
//        emoji.put("\uD83D\uDC1F", " ");
//        emoji.put("\uD83D\uDC33", " ");
//        emoji.put("\uD83D\uDC2C", " ");
//        emoji.put("\uD83D\uDC90", " ");
//        emoji.put("\uD83C\uDF38", " ");
//        emoji.put("\uD83C\uDF37", " ");
//        emoji.put("\uD83C\uDF40", " ");
//        emoji.put("\uD83C\uDF39", " ");
//        emoji.put("\uD83C\uDF3B", " ");
//        emoji.put("\uD83C\uDF3A", " ");
//        emoji.put("\uD83C\uDF41", " ");
//        emoji.put("\uD83C\uDF43", " ");
//        emoji.put("\uD83C\uDF42", " ");
//        emoji.put("\uD83C\uDF34", " ");
//        emoji.put("\uD83C\uDF35", " ");
//        emoji.put("\uD83C\uDF3E", " ");
//        emoji.put("\uD83D\uDC1A", " ");
//        emoji.put("\u0031\u20E3", " ");
//        emoji.put("\u0032\u20E3", " ");
//        emoji.put("\u0033\u20E3", " ");
//        emoji.put("\u0034\u20E3", " ");
//        emoji.put("\u0035\u20E3", " ");
//        emoji.put("\u0036\u20E3", " ");
//        emoji.put("\u0037\u20E3", " ");
//        emoji.put("\u0038\u20E3", " ");
//        emoji.put("\u0039\u20E3", " ");
//        emoji.put("\u0030\u20E3", " ");
//        emoji.put("\u0023\u20E3", " ");
//        emoji.put("\u2B06", " ");
//        emoji.put("\u2B07", " ");
//        emoji.put("\u2B05", " ");
//        emoji.put("\u27A1", " ");
//        emoji.put("\u2197", " ");
//        emoji.put("\u2196", " ");
//        emoji.put("\u2198", " ");
//        emoji.put("\u2199", " ");
//        emoji.put("\u25C0", " ");
//        emoji.put("\u25B6", " ");
//        emoji.put("\u23EA", " ");
//        emoji.put("\u23E9", " ");
//        emoji.put("\uD83C\uDD97", " ");
//        emoji.put("\uD83C\uDD95", " ");
//        emoji.put("\uD83D\uDD1D", " ");
//        emoji.put("\uD83C\uDD99", " ");
//        emoji.put("\uD83C\uDD92", " ");
//        emoji.put("\uD83C\uDFA6", " ");
//        emoji.put("\uD83C\uDE01", " ");
//        emoji.put("\uD83D\uDCF6", " ");
//        emoji.put("\uD83C\uDE35", " ");
//        emoji.put("\uD83C\uDE33", " ");
//        emoji.put("\uD83C\uDE50", " ");
//        emoji.put("\uD83C\uDE39", " ");
//        emoji.put("\uD83C\uDE2F", " ");
//        emoji.put("\uD83C\uDE3A", " ");
//        emoji.put("\uD83C\uDE36", " ");
//        emoji.put("\uD83C\uDE1A", " ");
//        emoji.put("\uD83C\uDE37", " ");
//        emoji.put("\uD83C\uDE38", " ");
//        emoji.put("\uD83C\uDE02", " ");
//        emoji.put("\uD83D\uDEBB", " ");
//        emoji.put("\uD83D\uDEB9", " ");
//        emoji.put("\uD83D\uDEBA", " ");
//        emoji.put("\uD83D\uDEBC", " ");
//        emoji.put("\uD83D\uDEAD", " ");
//        emoji.put("\uD83C\uDD7F", " ");
//        emoji.put("\u267F", " ");
//        emoji.put("\uD83D\uDE87", " ");
//        emoji.put("\uD83D\uDEBE", " ");
//        emoji.put("\u3299", " ");
//        emoji.put("\u3297", " ");
//        emoji.put("\uD83D\uDD1E", " ");
//        emoji.put("\uD83C\uDD94", " ");
//        emoji.put("\u2733", " ");
//        emoji.put("\u2734", " ");
//        emoji.put("\uD83D\uDC9F", " ");
//        emoji.put("\uD83C\uDD9A", " ");
//        emoji.put("\uD83D\uDCF3", " ");
//        emoji.put("\uD83D\uDCF4", " ");
//        emoji.put("\uD83D\uDCB9", " ");
//        emoji.put("\uD83D\uDCB1", " ");
        emoji.put("\u2648", " ");
        emoji.put("\u2649", " ");
        emoji.put("\u264A", " ");
        emoji.put("\u264B", " ");
        emoji.put("\u264C", " ");
        emoji.put("\u264D", " ");
        emoji.put("\u264E", " ");
        emoji.put("\u264F", " ");
        emoji.put("\u2650", " ");
        emoji.put("\u2651", " ");
        emoji.put("\u2652", " ");
        emoji.put("\u2653", " ");
//        emoji.put("\u26CE", " ");
//        emoji.put("\uD83D\uDD2F", " ");
//        emoji.put("\uD83C\uDD70", " ");
//        emoji.put("\uD83C\uDD71", " ");
//        emoji.put("\uD83C\uDD8E", " ");
//        emoji.put("\uD83C\uDD7E", " ");
//        emoji.put("\uD83D\uDD32", " ");
//        emoji.put("\uD83D\uDD34", " ");
//        emoji.put("\uD83D\uDD33", " ");
//        emoji.put("\uD83D\uDD5B", " ");
//        emoji.put("\uD83D\uDD50", " ");
//        emoji.put("\uD83D\uDD51", " ");
//        emoji.put("\uD83D\uDD52", " ");
//        emoji.put("\uD83D\uDD53", " ");
//        emoji.put("\uD83D\uDD54", " ");
//        emoji.put("\uD83D\uDD55", " ");
//        emoji.put("\uD83D\uDD56", " ");
//        emoji.put("\uD83D\uDD57", " ");
//        emoji.put("\uD83D\uDD58", " ");
//        emoji.put("\uD83D\uDD59", " ");
//        emoji.put("\uD83D\uDD5A", " ");
//        emoji.put("\u2B55", " ");
//        emoji.put("\u274C", " ");

//        emoji.put("\u2122", " ");
//        emoji.put("\uD83C\uDFE0", " ");
//        emoji.put("\uD83C\uDFEB", " ");
//        emoji.put("\uD83C\uDFE2", " ");
//        emoji.put("\uD83C\uDFE3", " ");
//        emoji.put("\uD83C\uDFE5", " ");
//        emoji.put("\uD83C\uDFE6", " ");
//        emoji.put("\uD83C\uDFEA", " ");
//        emoji.put("\uD83C\uDFE9", " ");
//        emoji.put("\uD83C\uDFE8", " ");
//        emoji.put("\uD83D\uDC92", " ");
//        emoji.put("\u26EA", " ");
//        emoji.put("\uD83C\uDFEC", " ");
//        emoji.put("\uD83C\uDF07", " ");
//        emoji.put("\uD83C\uDF06", " ");
//        emoji.put("\uD83C\uDFE7", " ");
//        emoji.put("\uD83C\uDFEF", " ");
//        emoji.put("\uD83C\uDFF0", " ");
//        emoji.put("\u26FA", " ");
//        emoji.put("\uD83C\uDFED", " ");
//        emoji.put("\uD83D\uDDFC", " ");
//        emoji.put("\uD83D\uDDFB", " ");
//        emoji.put("\uD83C\uDF04", " ");
//        emoji.put("\uD83C\uDF05", " ");
//        emoji.put("\uD83C\uDF03", " ");
//        emoji.put("\uD83D\uDDFD", " ");
//        emoji.put("\uD83C\uDF08", " ");
//        emoji.put("\uD83C\uDFA1", " ");
//        emoji.put("\u26F2", " ");
//        emoji.put("\uD83C\uDFA2", " ");
//        emoji.put("\uD83D\uDEA2", " ");
//        emoji.put("\uD83D\uDEA4", " ");
//        emoji.put("\u26F5", " ");
//        emoji.put("\u2708", " ");
//        emoji.put("\uD83D\uDE80", " ");
//        emoji.put("\uD83D\uDEB2", " ");
//        emoji.put("\uD83D\uDE99", " ");
//        emoji.put("\uD83D\uDE97", " ");
//        emoji.put("\uD83D\uDE95", " ");
//        emoji.put("\uD83D\uDE8C", " ");
//        emoji.put("\uD83D\uDE93", " ");
//        emoji.put("\uD83D\uDE92", " ");
//        emoji.put("\uD83D\uDE91", " ");
//        emoji.put("\uD83D\uDE9A", " ");
//        emoji.put("\uD83D\uDE83", " ");
//        emoji.put("\uD83D\uDE89", " ");
//        emoji.put("\uD83D\uDE84", " ");
//        emoji.put("\uD83D\uDE85", " ");
//        emoji.put("\uD83C\uDFAB", " ");
//        emoji.put("\u26FD", " ");
//        emoji.put("\uD83D\uDEA5", " ");
//        emoji.put("\u26A0", " ");
//        emoji.put("\uD83D\uDEA7", " ");
//        emoji.put("\uD83D\uDD30", " ");
//        emoji.put("\uD83C\uDFB0", " ");
//        emoji.put("\uD83D\uDE8F", " ");
//        emoji.put("\uD83D\uDC88", " ");
//        emoji.put("\u2668", " ");
//        emoji.put("\uD83C\uDFC1", " ");
//        emoji.put("\uD83C\uDF8C", " ");

    }

    public static EmojiMap getInstance() {
        return instance;
    }

    public Map<String, String> getMap() {
        return emoji;
    }
}
